"use client";

import React from "react";

interface ScriptDownloadProps {
    command: string;
    filename: string;
}

export function ScriptDownload({ command, filename }: ScriptDownloadProps) {
    const downloadScript = (ext: "bat" | "sh") => {
        let content = "";
        if (ext === "bat") {
            // Escape percentage signs for Batch files
            const escapedCommand = command.replace(/%/g, "%%");
            content = `@echo off\r\n\r\n:: Video Download Script Generated by YT Chapters\r\necho Starting download...\r\n\r\n${escapedCommand}\r\n\r\necho.\r\necho Done! Press any key to close.\r\npause >nul`;
        } else {
            content = `#!/bin/bash\n\n# Video Download Script Generated by YT Chapters\necho "Starting download..."\n\n${command}\n\necho "\nDone!"`;
        }

        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${filename}.${ext}`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="flex gap-4 pt-2">
            <button
                onClick={() => downloadScript("bat")}
                className="flex-1 bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded-lg font-medium transition-colors flex items-center justify-center gap-2"
            >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 22h14a2 2 0 0 0 2-2V7.5L14.5 2H6a2 2 0 0 0-2 2v4" /><polyline points="14 2 14 8 20 8" /><path d="M4.6 14.6l-1.2 2.4-1.2-2.4" /><path d="M10 17h-2v-4" /><path d="M6 14h2v2c0 1.1-.9 2-2 2H6" /></svg>
                Download .bat (Windows)
            </button>
            <button
                onClick={() => downloadScript("sh")}
                className="flex-1 bg-slate-700 hover:bg-slate-800 text-white py-2 px-4 rounded-lg font-medium transition-colors flex items-center justify-center gap-2"
            >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 22h14a2 2 0 0 0 2-2V7.5L14.5 2H6a2 2 0 0 0-2 2v4" /><polyline points="14 2 14 8 20 8" /><path d="M9 18l6-6-6-6" /></svg>
                Download .sh (Mac/Linux)
            </button>
        </div>
    );
}
